# Generated by Django 2.0.6 on 2018-06-14 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('org', models.CharField(max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('img_url', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('site', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('img_url', models.CharField(max_length=128)),
                ('short_desc', models.CharField(max_length=256)),
                ('desc', models.TextField()),
                ('manufacturer', models.CharField(max_length=128)),
                ('year', models.CharField(max_length=4)),
                ('broken', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vlab.Device')),
            ],
            options={
                'verbose_name_plural': 'devicebookings',
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('desc', models.TextField(max_length=512)),
                ('deprecated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'experiments',
            },
        ),
        migrations.CreateModel(
            name='ExperimentCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('desc', models.TextField(max_length=512)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vlab.Experiment')),
            ],
            options={
                'verbose_name_plural': 'experimentconditions',
            },
        ),
        migrations.CreateModel(
            name='ExperimentOutputParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('measure', models.CharField(max_length=128)),
                ('accuracy', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'experimentoutputparameters',
            },
        ),
        migrations.CreateModel(
            name='ExperimentSourceRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vlab.Experiment')),
            ],
            options={
                'verbose_name_plural': 'experimentsourcerequirements',
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('contact_name', models.CharField(max_length=128)),
                ('img_url', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('site', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=20)),
                ('score', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'labs',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=128, unique=True)),
                ('date', models.DateField()),
                ('task_status', models.CharField(max_length=128)),
                ('delivery_status', models.CharField(max_length=128)),
                ('delivery_ticket', models.CharField(max_length=128)),
                ('delivery_type', models.IntegerField()),
                ('source_origin_country', models.CharField(max_length=128)),
                ('source_origin_city', models.CharField(max_length=128)),
                ('source_origin_address', models.CharField(max_length=256)),
                ('source_origin_phone', models.CharField(max_length=20)),
                ('source_origin_responsible', models.CharField(max_length=128)),
                ('dest_origin_country', models.CharField(max_length=128)),
                ('dest_origin_city', models.CharField(max_length=128)),
                ('dest_origin_address', models.CharField(max_length=256)),
                ('dest_origin_phone', models.CharField(max_length=20)),
                ('dest_origin_responsible', models.CharField(max_length=128)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vlab.Customer')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vlab.Experiment')),
            ],
            options={
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('desc', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('special_status', models.IntegerField(default=0)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vlab.Customer')),
            ],
            options={
                'verbose_name_plural': 'problems',
            },
        ),
        migrations.CreateModel(
            name='ProblemComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('rank_status', models.IntegerField(default=0)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vlab.Customer')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vlab.Problem')),
            ],
            options={
                'verbose_name_plural': 'problemcomments',
            },
        ),
        migrations.CreateModel(
            name='ProblemCommentComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('rank_status', models.IntegerField(default=0)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vlab.Customer')),
                ('problem_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vlab.ProblemComment')),
            ],
            options={
                'verbose_name_plural': 'problemcommentcomments',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('comments', models.TextField()),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vlab.Lab')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vlab.Customer')),
            ],
            options={
                'verbose_name_plural': 'reviews',
            },
        ),
        migrations.AddField(
            model_name='experiment',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vlab.Lab'),
        ),
        migrations.AddField(
            model_name='device',
            name='experiments',
            field=models.ManyToManyField(to='vlab.Experiment'),
        ),
        migrations.AddField(
            model_name='device',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vlab.Lab'),
        ),
    ]
