# Generated by Django 2.0.6 on 2018-06-16 07:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vlab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('published', models.BooleanField(default=False)),
                ('desc', models.TextField()),
                ('rank_status', models.IntegerField(default=0)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vlab.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AuctionOutputParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('measure', models.CharField(max_length=128)),
                ('sufficient_accuracy', models.CharField(max_length=128)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vlab.Auction')),
            ],
            options={
                'verbose_name_plural': 'auctionoutputparameters',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to='docs/')),
                ('for_deleting', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'documents',
            },
        ),
        migrations.AddField(
            model_name='experimentoutputparameter',
            name='experiment',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='vlab.Experiment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionbid',
            name='documents',
            field=models.ManyToManyField(to='vlab.Document'),
        ),
        migrations.AddField(
            model_name='auctionbid',
            name='experiment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vlab.Experiment'),
        ),
        migrations.AddField(
            model_name='auction',
            name='documents',
            field=models.ManyToManyField(to='vlab.Document'),
        ),
    ]
